    server:
      port: 8082
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/adminapp-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
        username: root
        password:
      application:
        name: spring-admin
      jpa:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        properties:
          hibernate:
            format_sql: true